function spikes(action)

%**********************************************************************************
% This Program will allow generation of PSTH and other spike
% measurements for up to 3 variables.
%
% [rowland]	[0.91 Now supports single independent variables 				(Dec 2000)	]
% [ian] 	[0.92 Updated it to use a newer binning routine 				(Dec 2000)	]
% [ian]		[1.0  Fixed trial selection bugs								(Feb 2001)  ]
% [ian]	 	[1.1  Added Burst Analysis to Spike Data						(Feb 2001)  ]
% [ian]	 	[1.2  Add temporal anal until roland movie fix					(Mar 2001)  ]
% [ian]	 	[1.5  Added error bars to tuning curves							(Mar 2001)  ]
% [ian]	 	[1.51 Added controls for Axis values							(Mar 2001)  ]
% [ian]	 	[1.52 Enhanced Burst Analysis for Wei							(Apr 2001)  ]
% [ian]	 	[1.53 Prepare to change to VSX data loading						(May 2001)  ]
% [ian]	 	[1.54 Added text load,single psth plot,bug fix					(May 2001)  ]
% [rowland] [1.6  Added interface with VSX to load smr files				(Jul 2001)  ]
% [ian]	 	[1.61 Finally allowed LSD to work with single modulation data 	(Dec 2001)  ]
% [ian]	 	[1.62 Fixed several bugs in different places					(Jan 2002)  ]
% [ian]	 	[1.63 Big Matlab Based error workround, note waitbar has been disabled and questdlg removed (Jan 2002) ]
% [ian]	 	[1.64 Minor tweaks												(Feb 2002)  ]
% [ian]	 	[1.65 Rearranged and some small fixes - FFT now works! 			(Apr 2002)  ]
% [ian]	 	[1.666 Plot all PSTHs uses the measured bins for display 		(May 2002)  ]
% [ian]		[1.7.1 Added the option to convolve PSTH with gaussian kernal   (July 2002)	]
% [ian]     [1.7.2 Partially added non-proportional plotting (only for unsmoothed data and 2D plots (Sep 2002)    ]
% [ian]     [1.7.3 Small fixes for Matlab V7.1                              (Sep 2005)    ]
% [ian]		[1.7.4 Implemented 0 variable loading support					(Nov 2005)	]
% [ian]		[1.7.5 Got rid of dependency on Frogbit!						(Nov 2005)	]
% [ian]		[1.7.6 Added Report Generation integration with spikereport		(Nov 2005)	]
% [ian]		[1.7.7 Can plot out and juggle any variable selection from 0-3  (Nov 2005)	]
% [ian]		[1.7.8 Small fixes															(Dec 2005)	]
% [ian]		[1.7.9 (Re)add the quick temporal analysis						(Feb 2006) ]
%
%
%**********************************************************************************


%-----------------------------------Global Variable Definitions----------------------------

global sv				%this holds many of the GUI interaction variables
global data				%this is the main data structure
global rlist			%this holds the cell list reports generated by spikereport
global mint				%the minimum selected time
global maxt				%the maximum selected time
global automeasure
global txtcomment		%these store vsx generated data info text files
global txtprotocol		%same

%---------------------------------------------------Start------------------------------------------

if nargin<1;
	action='Initialize';
end

switch(action)			%As we use the GUI this switch allows us to respond to the user input

	%----------------------------------------------------------------------
case 'Initialize'
	%----------------------------------------------------------------------
	sv=[];
	data=[];
	
	sv.version='SPIKES: V1.82a';
	sv.uihandle=spikes_UI; %our GUI file
	figpos(2);	%position the figure
	set(sv.uihandle,'Name', [sv.version ' | Started at ' datestr(now)]);
	colormap(jet(256)); %this gives us a much higher resolution colormap
	%-------The following sv structure sets up the GUI interface structure--
	sv.BinWidth=10;
	sv.StartMod=1;
	sv.EndMod=Inf;
	sv.StartTrial=1; 
	sv.EndTrial=Inf;
	sv.Wrapped=1;
	sv.AnalysisMethod=1;	
	sv.firstunit=1;
	sv.loop=0;
	sv.HeldVariable=3;
	sv.HeldValue=1;
	sv.PropAxis=1;
	sv.PlotType='Raw Data';
	sv.ShadingType='interp';
	sv.Lighting='phong';
	sv.SmoothType='none';
	sv.SmoothValue=5;
	sv.CMap='jet';
	sv.LightAdd='none';
	sv.reload='no';
	sv.loadtype='';
	sv.loaded='no';
	sv.ErrorMode='Standard Error';
	sv.ticks='out';
	sv.layer='top';
	sv.box='on';
	sv.auto='no';
	sv.xval=1;
	sv.yval=1;
	sv.zval=1;
	sv.xlock=0;
	sv.ylock=0;
	sv.zlock=0;
	sv.xholdold=0;
	sv.yholdold=0;
	sv.zholdold=0;
	%-----------------------------------------------------------------------
	sv.mintime=-inf;
	mint=-inf; 				%min time
	sv.maxtime=inf;
	maxt=inf; 				%max time
	automeasure=0; 			%used by temporal movie creator

	history='';
	shistory='';
	paths='';
	if exist('c:\history.mat','file') == 2
		load 'c:\history.mat';
		set(gh('spikehistory'),'String',history);
	else
		set(gh('spikehistory'),'String',' ');
	end
	if exist('c:\shistory.mat','file') == 2
		load('c:\shistory.mat');
		if length(shistory)>10
			set(gh('SSliceHistory'),'String',shistory(end-9:end));
		else
			set(gh('SSliceHistory'),'String',shistory);
		end
	end
	
	set(gh('CMapMenu'),'String',{'jet';'jet2';'hot';'rbmap';'gray';'gray1';'gray2';'hsv';'prism';'colorcube';'bone';'copper';'pink';'summer';'winter';'autumn';'spring'});
	set(gh('ErrorMenu'),'String',{'Standard Error';'Standard Deviation';'Fano Factor';'Coefficient of Variation';'2 StdDevs';'3 StdDevs';'2 StdErrs';'Variance'});
	set(gh('ErrorMenu'),'Value',1);
	set(gh('AxisMenu'),'String',{'auto';'on';'off';'normal';'tight';'vis3d';'equal';'square';'image';'------------';'Axis Above Data';'Axis Below Data';'Ticks Facing In';'Ticks Facing Out';'Axis Box On';'Axis Box Off';'Flip X and Y';'Y Axis Normal';'Y Axis Reverse';'------------';'Auto Renderer';'Painters Renderer';'ZBuffer Renderer';'OpenGL Renderer'});
	set(gh('AnalysisMenu'),'String',{'Mean';'Peak 3 bin';'Peak 1 Bin';'Count';'A/B Ratio';'FFT'});
	set(gh('SmoothingMenu'),'String',{'none';'cubic';'spline';'linear';'nearest'});
	set(gh('SPlotMenu'),'String',{'ISI';'Intervalogram';'Raster';'PSTH';'Fanogram';'Curve';'Surface'});
	set(gh('SPlotMenu'),'Value',7);
	set(gh('STypeMenu'),'String',{'Raw Data';'Mesh';'CheckerBoard';'CheckerBoard+Contour';'Surface';'Lighted Surface';'Surface+Contour';'Contour';'Filled Contour';'Waterfall';'Rectangle Plot'});
	set(gh('AnalMenu'),'String',{'========';'Plot All PSTHs';'Plot Single PSTH';'Plot All ISIs';'Metric Space';'Metric Space (Interval)';'Half-Width';'Difference of Gaussian';'Gabor Fit';'Burst Ratio';'Plateau Analysis';'Temporal Movie';'Temporal Analysis';'Area Analysis';'2D Curves';'Tuning Curves';'Surround Suppression'});
	set(gcf,'DefaultLineLineWidth',1.5);
	set(gcf,'DefaultAxesLineWidth',1.5);
	set(gcf,'defaultaxesfontname','Georgia');
	set(gcf,'defaulttextfontname','Georgia');
	set(gcf,'defaulttextfontsize',8);
	set(gca,'Layer','top');	%ticks go over data
	set(gca,'TickDir','out');  %get ticks going out
	set(gh('SMinEdit'),'UserData','no');						%these initialize the min and max time boxes
	set(gh('SMaxEdit'),'UserData','no');						%...
	set(gca,'tag','SpikeFigMainAxes');						%make sure axes have right name
	set(gcf,'tag','SpikeFig');									%ditto for the figure
	if exist('c:\spiketemp','file');delete('c:\spiketemp'); end %delete any previous data

	sv.matlabroot=regexprep(matlabroot,'Program files','Progra~1','ignorecase');
	if regexp(sv.matlabroot,'2006b')
		sv.matlabroot=regexprep(sv.matlabroot,'2006b','2007a');
	end
	
	if isfield(paths,'matsavepath')
		cv.matsavepath=paths.matsavepath;
	end
	if isfield(paths,'matloadpath')
		sv.matloadpath=paths.matloadpath;
	end
	if isfield(paths,'dataloadpath')
		sv.dataloadpath=paths.dataloadpath;
		cd(sv.dataloadpath);
	end
	  
 	%-----------------------------------------------------------------------------------------
case 'ChoosePlot'
	%-----------------------------------------------------------------------------------------

	ChoosePlot;

	%------------------------------------------Loading the data-------------------------------------
case 'Load'
	%-----------------------------------------------------------------------------------------------
	close(gh('MovieToolFig')); 	
	
	startclock=clock;
	startcpu=cputime;
	
	if strcmp(sv.reload,'yes')								%see if we have to reload the data or not
		set(gh('LoadText'),'String','Reloading Data');
		meta=data.meta;
		info=data.info;
		t=data.filetype;
		data=struct;
		data.meta=meta;
		data.info=info;
		data.filetype=t;
		sv.reload='no';
	else
		if ~strcmp(sv.auto,'report'); sv.auto='no'; end
		set(gh('LoadText'),'String','Data Loading');		
		%This checks to see if we are called with a load history or to open new data.
		n=regexpi(sv.reload,'^(?<name>[^|]+)(?:.+)(?<num>\d)','names'); %part of the file history reloading mechanism
		if ~isempty(n) %&& ~strcmp(sv.loadtype,'') %we already have a path			
			switch sv.loadtype
			case 'previous'
				sv.loadtype='';
				nn=regexpi(n.name,'[^\d\\]+(?<num>\d\d)\.(?<ext>txt|smr)','names');
				number=str2double(nn.num)-1;
				ind=regexp(n.name,'/'); %we only want to replave the number for the filename and preceding directory, not anywhere else in the path
				if number<10
					name=regexprep(n.name(ind(end-1)+1:end), nn.num, ['0' num2str(number)]);
					name=[n.name(1:ind(end-1)) name]; %rebuild the full path and file
				else
					name=regexprep(n.name(ind(end-1)+1:end), nn.num, num2str(number));
					name=[n.name(1:ind(end-1)) name]; %rebuild the full path and file
				end
				if ~strcmp(filesep,'/'); name=regexprep(name,'\/','\\'); end
				[p,basefilename,e]=fileparts(name);
				name=[p '.smr'];
				if ~exist(name,'file')
					errordlg('No previous file');
					error('No previous file');
				end
				sv.auto='yes';
			case 'next'
				sv.loadtype='';
				nn=regexpi(n.name,'[^\d\\]+(?<num>\d\d)\.(?<ext>txt|smr)','names');
				number=str2double(nn.num)+1;
				ind=regexp(n.name,'/'); %we only want to replave the number for the filename and preceding directory, not anywhere else in the path
				if number<10					
					name=regexprep(n.name(ind(end-1)+1:end), nn.num, ['0' num2str(number)]);
					name=[n.name(1:ind(end-1)) name]; %rebuild the full path and file
				else
					name=regexprep(n.name(ind(end-1)+1:end), nn.num, num2str(number));
					name=[n.name(1:ind(end-1)) name]; %rebuild the full path and file
				end
				if ~strcmp(filesep,'/'); name=regexprep(name,'\/','\\'); end
				[p,basefilename,e]=fileparts(name);
				name=[p '.smr'];
				if ~exist(name,'file')
					errordlg('No next file');
					error('No next file');
				end
				sv.auto='yes';
				otherwise
				name=n.name(1:end-1);
			end
			[p,basefilename,e]=fileparts(name);
			pn=[p filesep];
			fn=[basefilename e];
			sv.firstunit=str2double(n.num);
			set(gh('CellMenu'),'Value',str2double(n.num));
			sv.reload='no';
		else %we need the user to specify a file
			[fn,pn]=uigetfile({'*.smr;*.txt;*.doc','All Spikes Filetypes (*.smr *.txt *.doc)';'*.smr','VS RAW DATA File (SMR)';'*.txt','VSX Output File (TXT)';'*.doc','XCor Output File (DOC)';'*.*','All Files'},'Select File Type to Load:');
			if isequal(fn,0)||isequal(pn,0);set(gh('LoadText'),'String','No Data Loaded');errordlg('No File Selected or Found!');error('File was not selected by user / not found.');end
			[p,basefilename,e]=fileparts([pn fn]);
		end		
		
		%we have a file so we reset our data and axes
		data=struct;
		cla;  reset(gca);  set(gca,'Tag','SpikeFigMainAxes');	%this resets the axis
		set(gh('SpikeMenu'),'Value',1); %resets the spike selector menu to all spikes
		automeasure=0;
		
		if regexpi(e,'\.smr')
			if (strcmp(sv.auto,'report') || strcmp(sv.auto,'yes') ) && isdir([p filesep basefilename])
				pn2=basefilename;
				data.filetype = 'txt';
			else
				if isdir([p filesep basefilename]) %stops annoying "directory alread exists" messages
					cd('c:\');
					disp('Deleted existing directory...');
					rmdir([p filesep basefilename],'s');
					cd(p);
				end
				s=dos([sv.matlabroot,'\user\various\vsx\vsx.exe ',pn,fn]);
				pn2 = fn(1:find(fn(:)=='.')-1);
				s=dos(['dir ',pn,pn2]);
				if s~=0; error('Sorry VSX cannot load the data!!! Make sure files do not have the read-only attribute set...'); end
				data.filetype = 'smr';
			end
			data.meta=loadvstext(strcat(pn,pn2,filesep,pn2,'.txt'));
			txtcomment=textread(strcat(pn,pn2,filesep,pn2,'.cmt'),'%s','delimiter','\n','whitespace','');
			txtprotocol=textread(strcat(pn,pn2,filesep,pn2,'.prt'),'%s','delimiter','\n','whitespace','');
			data.info=['===============PROTOCOL================';txtprotocol(2:end);'===============COMMENTS================';txtcomment(9:end)];
		elseif regexpi(e,'\.txt')
			data.filetype = 'txt';
			data.meta=loadvstext([pn,fn]);
			txtcomment=textread([pn,strrep(fn,'.txt','.cmt')],'%s','delimiter','\n','whitespace','');
			txtprotocol=textread([pn,strrep(fn,'.txt','.prt')],'%s','delimiter','\n','whitespace','');
			data.info=['===============PROTOCOL================';txtprotocol(2:end);'===============COMMENTS================';txtcomment(9:end)];
		elseif regexpi(e,'\.doc')
			errordlg('Sorry, .doc files are an old format not safe to use, please use the .SMR!');
			error('Sorry, .doc files are an old format not safe to use, please use the .SMR!');
			%dos([sv.matlabroot,'\user\Frogbit\frogbitrun.exe ', sv.matlabroot,'\user\Frogbit\spikestrip1.FB ',pn,fn,]);
			%data.filetype = 'doc';
		elseif regexpi(e,'\.mat')
			sv.pn=pn;
			sv.fn=fn;
			spikes('Load MAT');
			return;
		else
			errordlg('Sorry, unsupported file type loaded!')
			error('File selection error, unsupported file type loaded!')
		end
	end
	[p,basefilename,e]=fileparts(data.meta.filename);	%seperate out the file from the path
	cd(p);												%change to the directory where all the spike time files live
	sv.dataloadpath=p;
	data.meta.filename(data.meta.filename=='\')='/';	%stops annoying TeX interpertation errors
	t=find(data.meta.filename=='/');
	data.runname=data.meta.filename((t(end-2))+1:t(end));

	silence_before_burst 	= str2double(get(gh('silence'),'String'))*10;
	first_isi				= str2double(get(gh('firstisi'),'String'))*10;
	subsequent_isi	   		= str2double(get(gh('subsisi'),'String'))*10;
	number_burst			= str2double(get(gh('numberspikes'),'String'));
	
	if (get(gh('SCutTransient'),'Value')>0) %this gets a time for optinally cutting the first transient out of the data
		cuttime=str2double(get(gh('STransientValue'),'String'))*10; %*10 converts into raw timebase from milliseconds
	else
		cuttime=0;
	end

	data.numvars=data.meta.numvars;
	data.protocol.name=data.meta.protocol;
	data.protocol.desc=data.meta.description;
	data.protocol.filecomm=data.meta.comments;
	data.protocol.date=data.meta.date;
	data.repeats=data.meta.repeats;
	data.error=[];

	if strcmp(data.filetype,'smr') || strcmp(data.filetype,'txt')
		data.cycles=data.meta.cycles;
		data.trialtime=data.meta.trialtime;
		data.modtime=data.meta.modtime;
		if isfield(data.meta,'tempfreq')
			data.tempfreq=data.meta.tempfreq;
		else
			data.tempfreq=[];
		end
	end

	switch data.numvars
	case 0   %this means we have no variables
		%Setup GUI
		sv.yholdold=0;
		sv.xholdold=0;
		sv.zholdold=0;
		set(gh('HoldXText'),'String',' ');
		set(gh('XHoldMenu'),'Value',1);
		set(gh('XHoldMenu'),'String',' ');
		set(gh('XHoldMenu'),'Enable','off');
		set(gh('XHoldCheck'),'Enable','off');
		set(gh('HoldYText'),'String',' ');
		set(gh('YHoldMenu'),'Value',1);
		set(gh('YHoldMenu'),'String',' ');
		set(gh('YHoldMenu'),'Enable','off');
		set(gh('YHoldCheck'),'Enable','off');
		set(gh('HoldZText'),'String',' ');
		set(gh('ZHoldMenu'),'Value',1);
		set(gh('ZHoldMenu'),'String',' ');
		set(gh('ZHoldMenu'),'Enable','off');
		set(gh('ZHoldCheck'),'Enable','off');

		%%%Disenables the 3D plotting options menus
		if get(gh('SPlotMenu'),'Value')>6; set(gh('SPlotMenu'),'Value',6); end
		set(gh('SPlotMenu'),'String',{'ISI';'Intervalogram';'Raster';'PSTH';'Fanogram';'Point'});		
		set(gh('STypeMenu'),'Enable','off');
		set(gh('CMapMenu'),'Enable','off');
		set(gh('ShadingMenu'),'Enable','off');
		set(gh('LightMenu'),'Enable','off');
		set(gh('LightingMenu'),'Enable','off');
		set(gh('RotateButton'),'Enable','off');
		set(gh('CMapButton'),'Enable','off');
		set(gh('LabelButton'),'Enable','off');
		set(gh('ColorEdit'),'Enable','off');
		set(gh('CheckBox1'),'Enable','off');
		set(gh('SmoothingMenu'),'Enable'28 19:51:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 19:51:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:51:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 19:51:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:51:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 19:54:01 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        164
    
INFO    [Fri Sep 28 19:56:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 19:56:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:56:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 19:56:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 19:56:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:01:50 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        164
    
INFO    [Fri Sep 28 20:01:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:01:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:01:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:01:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:01:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:06:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:06:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:06:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:06:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:06:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:09:40 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        164
    
INFO    [Fri Sep 28 20:11:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:11:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:11:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:11:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:11:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:16:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:16:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:16:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:16:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:16:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:17:31 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        164
    
INFO    [Fri Sep 28 20:21:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:21:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:21:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:21:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:21:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:25:22 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        164
    
INFO    [Fri Sep 28 20:26:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:26:51 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:26:51 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:26:51 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:26:51 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:31:04 2007 UserInterface\Quasimode\__init__.pyc L294]: Created a new quasimode window!
INFO    [Fri Sep 28 20:31:04 2007 UserInterface\Quasimode\__init__.pyc L356]: Deleting the quasimode window.
INFO    [Fri Sep 28 20:31:04 2007 UserInterface\Messages\PrimaryWindow.pyc L183]: newMessage: <p><command>s</command> is not a command.</p><caption>Did you mean <command>manage beta products</command>?</caption>
INFO    [Fri Sep 28 20:31:05 2007 UserInterface\Messages\__init__.pyc L315]: Primary message dismissed.
INFO    [Fri Sep 28 20:31:51 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:31:52 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:31:52 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:31:52 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:31:52 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:32:57 2007 UserInterface\Quasimode\__init__.pyc L294]: Created a new quasimode window!
INFO    [Fri Sep 28 20:32:58 2007 UserInterface\Quasimode\__init__.pyc L356]: Deleting the quasimode window.
INFO    [Fri Sep 28 20:33:00 2007 UserInterface\Quasimode\__init__.pyc L294]: Created a new quasimode window!
INFO    [Fri Sep 28 20:33:00 2007 UserInterface\Quasimode\__init__.pyc L356]: Deleting the quasimode window.
INFO    [Fri Sep 28 20:33:12 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        165
    
INFO    [Fri Sep 28 20:36:52 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:36:52 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:36:52 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:36:52 2007 Utils\UpdateManager.pyc L521]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:36:52 2007 Utils\AutoUpdateThread.pyc L103]: AutoUpdateThread: waiting 300 seconds.
INFO    [Fri Sep 28 20:41:02 2007 EnsoApp.pyc L128]: MEMOIZE USAGE STATISTICS:

     Number of functions which used memoizing:         4
     Number of unique function values recorded:        165
    
INFO    [Fri Sep 28 20:41:52 2007 Utils\AutoUpdateThread.pyc L83]: AutoUpdateThread: checking for updates.
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: Trying to open url 'http://update.humanized.com/'  with proxy: None  with credentials: user=None, password=[not showing password]
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: 
INFO    [Fri Sep 28 20:41:52 2007 Utils\UpdateManager.pyc L266]: Non-fatal error communicating w/ update server: urllib2.URLError - <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: A NetworkingError occurred. Traceback follows.
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: Traceback (most recent call last):
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "Humanized\Networking.pyc", line 396, in _tryOpener
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 358, in open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 376, in _open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 337, in _call_chain
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 1021, in http_open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]:   File "urllib2.pyc", line 996, in do_open
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> L0]: URLError: <urlopen error (11001, 'getaddrinfo failed')>
INFO    [Fri Sep 28 20:41:52 2007 <sys.stderr> 